{{- if .Values.prometheusRules.enabled }}
{{- $defaultRulesEnabled := .Values.prometheusRules.defaultRulesEnabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "sophora-cluster-common.fullname" . }}
  labels: {{- include "sophora-cluster-common.labels" . | nindent 4 }}
spec:
  groups:
    - name: {{ template "sophora-cluster-common.fullname" $ }}
      rules:
        {{- if $defaultRulesEnabled }}
        - alert: NoPrimarySophoraServer
          for: {{ .Values.prometheusRules.config.NoPrimarySophoraServer.for }}
          expr: 'absent(sophora_server_replication_mode{namespace="{{ .Release.Namespace }}"} == 1)'
          labels:
            severity: critical
            namespace: "{{ .Release.Namespace }}"
          annotations:
            summary: The Sophora Cluster has no primary.
            description: No primary server elected in the cluster.
            runbook_url: 'https://github.com/subshell/helm-charts/blob/main/charts/sophora-cluster-common/alerting-runbook.md'
        - alert: SophoraReplicaServerNotInSync
          for: {{ .Values.prometheusRules.config.SophoraReplicaServerNotInSync.for }}
          expr: 'max(sophora_server_source_time{namespace="{{ .Release.Namespace }}"} and sophora_server_is_primary_server{namespace="{{ .Release.Namespace }}"} == 1) - ignoring(pod) group_right max by (pod) (sophora_server_source_time{namespace="{{ .Release.Namespace }}"}  and sophora_server_state{namespace="{{ .Release.Namespace }}"} == 2 and sophora_server_replication_mode{namespace="{{ .Release.Namespace }}"} == 2) > 60000'
          labels:
            severity: high
            namespace: "{{ .Release.Namespace }}"
          annotations:
            summary: Replica is not in sync
            description: The server  "{{`{{ $labels.pod }}`}}" is not in sync.
            runbook_url: 'https://github.com/subshell/helm-charts/blob/main/charts/sophora-cluster-common/alerting-runbook.md'
        - alert: SophoraStagingServerNotInSync
          for: {{ .Values.prometheusRules.config.SophoraStagingServerNotInSync.for }}
          expr: '(sophora_server_source_time{namespace="{{ .Release.Namespace }}"} and on(pod) (sophora_server_state{namespace="{{ .Release.Namespace }}"} == 3 or sophora_server_state{namespace="{{ .Release.Namespace }}"} == 4) and on(pod) sophora_server_replication_mode{namespace="{{ .Release.Namespace }}"} == 3) > 0'
          labels:
            severity: high
            namespace: "{{ .Release.Namespace }}"
          annotations:
            summary: Staging is not in sync
            description: The server  "{{`{{ $labels.pod }}`}}" is not in sync.
            runbook_url: 'https://github.com/subshell/helm-charts/blob/main/charts/sophora-cluster-common/alerting-runbook.md'
        - alert: MultiplePrimarySophoraServers
          for: {{ .Values.prometheusRules.config.MultiplePrimarySophoraServers.for }}
          expr: 'count(sophora_server_replication_mode{namespace="{{ .Release.Namespace }}"} == 1) > 1'
          labels:
            severity: critical
            namespace: "{{ .Release.Namespace }}"
          annotations:
            summary: The Sophora Cluster has more than one server claiming to be the primary.
            description: There are two primary servers in the cluster.
            runbook_url: 'https://github.com/subshell/helm-charts/blob/main/charts/sophora-cluster-common/alerting-runbook.md'
        {{- end }}
        {{- with .Values.prometheusRules.rules }}
        {{ tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
{{- end }}
