{{- if .Values.gcp.gatewayPolicy -}}
apiVersion: networking.gke.io/v1
kind: GCPGatewayPolicy
metadata:
  name: {{ .Values.gcp.gatewayPolicy.name }}
spec:
  default:
    {{- with .Values.gcp.gatewayPolicy.default.sslPolicy }}
    sslPolicy: "{{ . }}"
    {{- end }}
    {{- with .Values.gcp.gatewayPolicy.default.allowGlobalAccess }}
    allowGlobalAccess: "{{ . }}"
    {{- end }}
    {{- with .Values.gcp.gatewayPolicy.default.region }}
    region: "{{ . }}"
    {{- end }}
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ include "gateway.fullname" . }}
{{- end -}}
