apiVersion: v2
name: sophora-seo-check
description: Sophora SEO Check
type: application
version: 1.4.0
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "HTTPRoute configuration changed to a map of routes via httpRoutes{}. The previous httpRoute field has been removed (breaking change)!"

appVersion: 4.12.0
sources:
  - https://github.com/subshell/helm-charts/tree/main/charts/sophora-seo-check
home: https://subshell.com/sophora/modules/sophora-seo-check104.html
icon: https://subshell.com/logos/sophora-seo-check100~1x1.1683631781182.png

dependencies:
  - name: common
    version: "0.1.0"
    repository: "file://../common"
