{{- $labels := include "sophora-server.topLevelLabels" . -}}
{{- $svcPort := .Values.sophora.server.ports.http -}}
{{- template "common.httproutes" (dict "dot" . "labels" $labels "svcPort" $svcPort) }}
