apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "artifactory-cleanup.fullname" . }}
  labels:
    {{- include "artifactory-cleanup.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  jobTemplate:
    metadata:
      name: {{ include "artifactory-cleanup.fullname" . }}
      labels:
        {{- include "artifactory-cleanup.labels" . | nindent 8 }}
    spec:
      completions: {{ .Values.job.completions }}
      parallelism: {{ .Values.job.parallelism }}
      selector:
        matchLabels:
          {{- include "artifactory-cleanup.selectorLabels" . | nindent 6 }}
      suspend: 
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "artifactory-cleanup.labels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "artifactory-cleanup.serviceAccountName" . }}
          {{- with .Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              args:
                - artifactory-cleanup
                {{- if not .Values.cleanup.dryMode }}
                - '--destroy'
                {{- end }}
                {{- range .Values.args }}
                - {{ . | quote }}
                {{- end }}
              {{- with .Values.securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                {{- if .Values.artifactoryCredentials }}
                - name: ARTIFACTORY_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.artifactoryCredentials.secretName | quote }}
                      key: {{ .Values.artifactoryCredentials.usernameKey | quote }}
                - name: ARTIFACTORY_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.artifactoryCredentials.secretName | quote }}
                      key: {{ .Values.artifactoryCredentials.passwordKey | quote }}
                 {{- end }}
                {{- range .Values.env }}
                - {{ toYaml . | nindent 18 }}
                {{- end }}
              {{- with .Values.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              volumeMounts:
                - name: config-volume
                  mountPath: /app/artifactory-cleanup.yaml
                  subPath: artifactory-cleanup.yaml
              {{- with .Values.volumeMounts }}
                {{- toYaml . | nindent 16 }}
              {{- end }}
          volumes:
            - name: config-volume
              configMap:
                name: {{ include "artifactory-cleanup.fullname" . }}
          {{- with .Values.volumes }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
      {{- end }}
      {{- with .Values.podFailurePolicy }}
      podFailurePolicy:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      podReplacementPolicy: {{ .Values.job.podReplacementPolicy }}
      {{- with .Values.job.successPolicy }}
      successPolicy:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.job.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
      {{- end }}
  schedule: {{ .Values.schedule | quote }}
{{- /* optional */}}
  concurrencyPolicy: {{ .Values.concurrencyPolicy | quote }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  {{- if .Values.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
  {{- end }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  suspend: {{ .Values.suspend }}
  {{- if .Values.timeZone }}
  timeZone: {{ .Values.timeZone }}
  {{- end }}
