apiVersion: v2
name: planr-tools
description: A Helm chart for deploying the planr-tools applications
type: application
version: 1.3.4
appVersion: "5.1.1"
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Changed GCP HealthCheckPolicy to use numeric port instead of named port by default"
sources:
  - https://github.com/subshell/helm-charts/tree/main/charts/planr-tools
home: https://gitlab.com/subshell/kunden/planr-tools
