{{- $fullName := include "sophora-ugc.fullname" . -}}
{{- $serviceName := printf "%s-webapp" $fullName -}}
{{- $labels := include "sophora-ugc.labels" . -}}
{{- $svcPort := 80 -}}
{{- template "common.httproutes" (dict "dot" . "fullName" $fullName "labels" $labels "svcPort" $svcPort "svcName" $serviceName) }}
