{{- $fullName := include "sophora-ugc.fullname" . -}}
{{- $multimediaFullName := include "sophora-ugc-multimedia.fullname" . -}}
{{- $labels := include "sophora-ugc.labels" . -}}
{{- $svcPort := 80 -}}
{{- range $nameSuffix := (.Values.httpRoutes | keys | sortAlpha) }}
{{- $httpRoute := index $.Values.httpRoutes $nameSuffix }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-%s" $fullName $nameSuffix | trunc 63 | trimSuffix "-" }}
  labels:
    {{- $labels | nindent 4 }}
  {{- with $httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $httpRoute.parentRefs }}
  parentRefs:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $httpRoute.hostnames }}
  hostnames:
  {{- range $httpRoute.hostnames }}
    - {{ . | quote }}
  {{- end }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ $fullName }}-webapp
          port: {{ $svcPort }}
      {{- with $httpRoute.matches }}
      matches:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $httpRoute.filters }}
      filters:
      {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- if $.Values.ugcMultimedia.enabled }}
    - backendRefs:
        - name: {{ $multimediaFullName }}
          port: {{ default 80 ($.Values.ugcMultimedia.config.server).port }}
      matches:
        - path:
            type: PathPrefix
            value: /public/binary
    - backendRefs:
        - name: {{ $multimediaFullName }}
          port: {{ default 80 ($.Values.ugcMultimedia.config.server).port }}
      matches:
        - path:
            type: PathPrefix
            value: /public/multimedia
    - backendRefs:
        - name: {{ $multimediaFullName }}
          port: {{ default 80 ($.Values.ugcMultimedia.config.server).port }}
      matches:
        - path:
            type: PathPrefix
            value: /secure/binary
    - backendRefs:
        - name: {{ $multimediaFullName }}
          port: {{ default 80 ($.Values.ugcMultimedia.config.server).port }}
      matches:
        - path:
            type: PathPrefix
            value: /secure/multimedia
    - backendRefs:
        - name: {{ $multimediaFullName }}
          port: {{ default 80 ($.Values.ugcMultimedia.config.server).port }}
      matches:
        - path:
            type: PathPrefix
            value: /websocket/multimedia
    {{- end }}
---
{{- end }}
