{{- if .Values.ugc.managementService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sophora-ugc.fullname" . }}-management
  labels:
    {{- include "sophora-ugc.labels" . | nindent 4 }}
    sophora-ugc.service-type: management
spec:
  clusterIP: {{ .Values.service.management.clusterIP }}
  ports:
    - name: management
      port: {{ .Values.ugc.managementService.port }}
      targetPort: {{ .Values.ugc.managementService.port }}
      protocol: TCP
  selector:
    {{- include "sophora-ugc.selectorLabels" . | nindent 4 }}
{{- end }}