{{- $fullName := include "webclient.fullname" . -}}
{{- $labels := include "webclient.labels" . -}}
{{- $svcPort := .Values.service.port -}}
{{- range $key := (.Values.httpRoutes | keys | sortAlpha) }}
{{- $httpRoute := index $.Values.httpRoutes $key }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-%s" $fullName $key | trunc 63 | trimSuffix "-" }}
  labels:
    {{- $labels | nindent 4 }}
  {{- with $httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $httpRoute.parentRefs }}
  parentRefs:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $httpRoute.hostnames }}
  hostnames:
  {{- range $httpRoute.hostnames }}
    - {{ . | quote }}
  {{- end }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
      {{- with $httpRoute.matches }}
      matches:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $httpRoute.filters }}
      filters:
      {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}