apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ required "name is required" .Values.name }}
  labels:
    {{ include "opentelemetry-instrumentation.labels" . | nindent 4 }}
spec:
  exporter:
    endpoint: {{ required "exporter.endpoint is required" .Values.exporter.endpoint }}
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "{{ .Values.sampler.ratio }}"
  env:
    - name: OTEL_METRICS_EXPORTER
      value: "none"
    - name: OTEL_LOGS_EXPORTER
      value: "none"
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"
    - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
      value: "grpc"
