apiVersion: v2
name: sophora-ai
description: Sophora AI
type: application
version: 2.7.4
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "use readiness probe endpoint /actuator/health/readiness"
    - kind: added
      description: "add env MANAGEMENT_ENDPOINT_HEALTH_GROUP_READINESS_INCLUDE=sophora to add the sophora health indicator to the readiness group"
appVersion: 1.7.0
sources:
  - https://github.com/subshell/helm-charts/tree/main/charts/sophora-ai
home: https://subshell.com/sophora/modules/sophora-ai100.html
icon: https://subshell.com/logos/sophora-ai106~1x1.1728311176867.png
