{{- if .Values.gcp.healthCheck.enabled }}
---
{{- $fullName := include "o-neko-catnip.fullname" . -}}
{{- $labels := include "o-neko-catnip.labels" . -}}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ $fullName }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  default:
    config:
      type: HTTP
      healthCheck:
        {{- with .Values.gcp.healthCheck.port }}
        port: {{ . }}
        {{- end }}
        {{- with .Values.gcp.healthCheck.portName }}
        portName: {{ . | quote }}
        {{- end }}
        requestPath: {{ .Values.gcp.healthCheck.path | quote }}
      logConfig:
        enable: true
  targetRef:
    group: ""
    kind: Service
    name: {{ $fullName }}
{{- end }}
