apiVersion: v2
name: sophora-media-finder
description: A Helm chart for Sophora Media Finder
type: application
version: 0.6.0
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "HTTPRoute configuration changed to a map of routes via httpRoutes{}. The previous httpRoute field has been removed (breaking change)!"

appVersion: "5.x"
sources:
  - https://github.com/subshell/helm-charts/tree/main/charts/sophora-media-finder
home: https://subshell.com/sophora/modules/sophora-smf100.html
icon: https://subshell.com/logos/sophora-media-finder100~1x1.1728311057357.png

dependencies:
  - name: common
    version: "0.1.0"
    repository: "oci://ghcr.io/subshell/helm-charts"
