{{- if .Values.gcp.healthCheck.enabled }}
{{- range $appKey := (include "planr-tools.app-keys" $ | fromYaml).keys }}
{{- $component := index $.Values.applications $appKey }}
{{- if $component.enabled }}
---
{{- $fullName := include "planr-tools.componentFullname" (dict "root" $ "component" $component) -}}
{{- $labels := include "planr-tools.labels" (dict "root" $ "component" $component) -}}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ $fullName }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  default:
    config:
      type: HTTP
      healthCheck:
        {{- with $.Values.gcp.healthCheck.port }}
        port: {{ . }}
        {{- end }}
        {{- with $.Values.gcp.healthCheck.portName }}
        portName: {{ . | quote }}
        {{- end }}
        requestPath: {{ $.Values.gcp.healthCheck.path | quote }}
      logConfig:
        enable: {{ $.Values.gcp.healthCheck.logging }}
  targetRef:
    group: ""
    kind: Service
    name: {{ $fullName }}
{{- end }}
{{- end }}
