{{- if and .Values.gcp.enabled .Values.gcp.healthCheck.enabled }}
{{- $fullName := include "sophora-ugc-proxy.fullname" . -}}
{{- $labels := include "sophora-ugc-proxy.labels" . -}}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ $fullName }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        {{- with .Values.gcp.healthCheck.port }}
        port: {{ . }}
        {{- end }}
        {{- with .Values.gcp.healthCheck.portName }}
        portName: {{ . | quote }}
        {{- end }}
        requestPath: {{ .Values.gcp.healthCheck.path | quote }}
    logConfig:
      enabled: {{ .Values.gcp.healthCheck.logging }}
  targetRef:
    group: ""
    kind: Service
    name: {{ $fullName }}
{{- end }}