apiVersion: v1
kind: Service
metadata:
  name: {{ include "sophora-ugc-proxy.fullname" . }}-jolokia
  labels:
    {{- include "sophora-ugc-proxy.labels" . | nindent 4 }}
spec:
  clusterIP: {{ .Values.service.jolokia.clusterIP }}
  ports:
    - port: 1694
      targetPort: 1694
      protocol: TCP
      name: jolokia
  selector:
    {{- include "sophora-ugc-proxy.selectorLabels" . | nindent 4 }}