apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sophora-ugc-proxy.fullname" . }}-logback
  labels:
  {{- include "sophora-ugc-proxy.labels" . | nindent 4 }}
data:
  logback.xml: |
    {{- .Values.ugc.logback | nindent 4}}