apiVersion: v1
kind: Service
metadata:
  name: {{ include "sophora-ugc-proxy.fullname" . }}-proxy
  labels:
    {{- include "sophora-ugc-proxy.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.proxy.type }}
  loadBalancerIP: {{ .Values.service.proxy.loadBalancerIP }}
  ports:
    - port: 80
      targetPort: {{ default 8080 (.Values.ugcProxy.config.server).port }}
      protocol: TCP
  selector:
    {{- include "sophora-ugc-proxy.selectorLabels" . | nindent 4 }}