apiVersion: v2
name: sophora-cluster-common
description: A Helm chart containing some common resources useful for Sophora cloud setups
type: application
version: 1.8.2
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: "gRPC service port now has the correct appProtocol set to kubernetes.io/h2c"


appVersion: "4"
sources:
  - https://github.com/subshell/helm-charts/tree/main/charts/sophora-cluster-common
home: https://subshell.com/sophora/modules/sophora-server102.html
