apiVersion: v2
name: sophora-cluster-common
description: A Helm chart containing some common resources useful for Sophora cloud setups
type: application
version: 1.7.0
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Added support for GRPCRoute and gRPC-HTTPRoute resources to the Sophora cluster common chart"

appVersion: "4"
sources:
  - https://github.com/subshell/helm-charts/tree/main/charts/sophora-cluster-common
home: https://subshell.com/sophora/modules/sophora-server102.html
