apiVersion: v2
name: sophora-image-ai
description: Sophora Image AI
type: application
version: 2.6.5
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "use readiness probe endpoint /actuator/health/readiness"
    - kind: added
      description: "add env MANAGEMENT_ENDPOINT_HEALTH_GROUP_READINESS_INCLUDE=sophora to add the sophora health indicator to the readiness group"


appVersion: 5.1.0
sources:
  - https://github.com/subshell/helm-charts/tree/main/charts/sophora-image-ai
home: https://subshell.com/sophora/modules/sophora-image-ai100.html
icon: https://subshell.com/logos/sophora-image-ai104~1x1.1692715050244.png
