apiVersion: v2
name: sophora-schema-docs
description: Sophora Schema Docs
type: application
version: 2.5.0
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "HTTPRoute configuration changed to a map of routes via httpRoutes{}. The previous httpRoute field has been removed (breaking change)!"

appVersion: 5.0.0
sources:
  - https://github.com/subshell/helm-charts/tree/main/charts/sophora-schema-docs
home: https://subshell.com/sophora/modules/sophora-schema-docs100.html
icon: https://subshell.com/logos/sophora-schema-docs-logo100~1x1.1683632420967.png

dependencies:
  - name: common
    version: "0.1.0"
    repository: "oci://ghcr.io/subshell/helm-charts"
