apiVersion: v2
name: o-neko
description: A Helm chart for O-Neko
type: application
version: 2.3.4
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Changed GCP HealthCheckPolicy to use numeric port instead of named port by default"

appVersion: "1.8.2"
sources:
  - https://github.com/subshell/o-neko/
  - https://github.com/subshell/helm-charts/tree/main/charts/o-neko
