apiVersion: v2
name: o-neko
description: A Helm chart for O-Neko
type: application
version: 2.3.3
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: "Fixed GCP HealthCheckPolicy logConfig field name from `enable` to `enabled`"

appVersion: "1.8.2"
sources:
  - https://github.com/subshell/o-neko/
  - https://github.com/subshell/helm-charts/tree/main/charts/o-neko
