apiVersion: v2
name: sophora-linkchecker
description: Sophora Link Checker
type: application
version: 0.6.5
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "use readiness probe endpoint /actuator/health/readiness"
    - kind: added
      description: "add env MANAGEMENT_ENDPOINT_HEALTH_GROUP_READINESS_INCLUDE=sophora to add the sophora health indicator to the readiness group"

appVersion: 6.0.0
sources:
  - https://github.com/subshell/helm-charts/tree/main/charts/sophora-linkchecker
home: https://subshell.com/sophora/modules/sophora-linkchecker102.html
icon: https://subshell.com/logos/linkchecker108~1x1.1683632258069.png
