apiVersion: v2
name: sophora-contentapi
description: Sophora Content API
type: application
version: 1.4.1
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: "new release to make chart version available"

appVersion: 6.0.0
sources:
  - https://github.com/subshell/helm-charts/tree/main/charts/sophora-contentapi
