apiVersion: v2
name: sophora-contentapi
description: Sophora Content API
type: application
version: 1.4.3
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: "Fixed GCP HealthCheckPolicy logConfig field name from `enable` to `enabled`"

appVersion: 6.0.0
sources:
  - https://github.com/subshell/helm-charts/tree/main/charts/sophora-contentapi
