apiVersion: v2
name: sophora-metadata-supplier
description: Sophora Metadata Supplier (SMS)
type: application
version: 1.7.0
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "HTTPRoute configuration changed to a map of routes via httpRoutes{}. The previous httpRoute field has been removed (breaking change)!"

appVersion: '4.14.0'
sources:
  - https://github.com/subshell/helm-charts/tree/main/charts/sophora-metadata-supplier
home: https://subshell.com/sophora/modules/sophora-metadata-supplier100.html
icon: https://subshell.com/logos/sophora-metadata-supplier104~1x1.1683631937857.png

dependencies:
  - name: common
    version: "0.1.0"
    repository: "oci://ghcr.io/subshell/helm-charts/common"
