apiVersion: v2
name: sophora-ugc-proxy
description: A Helm chart for Kubernetes to install Sophora UGC Proxy connected to several Sophora UGC instances.

type: application

version: 1.3.2
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: "Fixed the GCP HealthCheckPolicy template to use the correct httpHealthCheck and logConfig fields"

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: '5.9.0'

# A list of URLs to source code for this project
sources:
  - https://github.com/subshell/helm-charts/tree/main/charts/sophora-ugc-proxy

# The URL of this projects home page
home: https://subshell.com/sophora/modules/sophora-ugc-comments-quizzes-votings-polls-forms100.html
# A URL to an SVG or PNG image to be used as an icon
icon: https://subshell.com/logos/ugc104~1x1.1683631915261.png
