service:
  proxy:
    type: LoadBalancer

authentication:
  secrets:
    - name: "subshell"
      s3bucket:
        name: s3bucket-secret
        accessKeyKey: s3bucket-access-key
        secretIdKey: s3bucket-secret-id

ugcProxy:
  image:
    repository: docker.subshell.com/ugc/ugc-proxy
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
  
  logback: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration scan="true">
        <jmxConfigurator />
        <!-- Propagate level settings to java.util.logging. -->
        <contextListener class="ch.qos.logback.classic.jul.LevelChangePropagator"/>
        <appender name="logfile" class="ch.qos.logback.core.rolling.RollingFileAppender">
            <File>/logs/ugc-proxy.log</File>
            <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
                <fileNamePattern>/logs/ugc-proxy.%d{yyyy-MM-dd}.log</fileNamePattern>
                <maxHistory>7</maxHistory>
            </rollingPolicy>
            <encoder>
                <pattern>[%d{"yyyy-MM-dd HH:mm:ss.SSSX",UTC}, %-5p] [%t] [%X{ID}] %.30c:%L: %m%n</pattern>
            </encoder>
        </appender>
        <appender name="errorLog" class="ch.qos.logback.core.rolling.RollingFileAppender">
            <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
                <level>ERROR</level>
            </filter>
            <File>/logs/error.log</File>
            <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
                <fileNamePattern>/logs/error.%d{yyyy-MM-dd}.log</fileNamePattern>
                <maxHistory>7</maxHistory>
            </rollingPolicy>
            <encoder>
                <pattern>[%d{"yyyy-MM-dd HH:mm:ss.SSSX",UTC}, %-5p] [%t] [%X{ID}] %.40c:%L: %m%n</pattern>
            </encoder>
        </appender>
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level [%X{ID}] %logger{36} - %msg%n</pattern>
            </encoder>
        </appender>
        <logger name="com.subshell.sophora.ugc.proxy" level="INFO" />
        <root level="WARN">
            <appender-ref ref="STDOUT" />
            <appender-ref ref="logfile" />
            <appender-ref ref="errorLog" />
        </root>
    </configuration>
  config:
    ugc-proxy:
      tenants:
        tenant1:
          s3:
            access-key-id: "xxx"
            secret-access-key: "xxx"
            host: "https://storage.googleapis.com"
            bucket-name: "ugc1-submissions"
          ugc-url: "ugc1.subshell.com"
        tenant2:
          s3:
            access-key-id: "xxx"
            secret-access-key: "xxx"
            host: "https://storage.googleapis.com"
            bucket-name: "ugc2-submissions"
          ugc-url: "ugc2.subshell.com"

  extraContainers: []

  extraInitContainers: []

# Additional environment variables can be defined here
env:

resources:
  requests:
    memory: "3.5G"
    cpu: "0.5"
  limits:
    memory: "3.5G"