name: Release Charts

on:
  workflow_dispatch:
  push:
    branches:
      - SUDO-610_oci_helmcharts
  workflow_run:
    workflows:
      - Test Charts
    branches:
      - main
    types:
      - completed

jobs:
  release:
    if: ${{ github.repository == 'subshell/helm-charts'}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      #- name: Run chart-releaser
      #  uses: helm/chart-releaser-action@v1.7.0
      #  env:
      #    CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Fake release
        run: |
          mkdir -p .cr-release-packages
          helm package charts/sophora-indexing-service --dependency-update --destination .cr-release-packages --debug
          touch .cr-release-packages/foo-1.2.3.tgz

      - name: Push charts to OCI registry
        if: ${{ hashFiles('.cr-release-packages/*.tgz') != '' }}
        run: |
          helm registry login ghcr.io/subshell --username subshell --password ${{ secrets.GITHUB_TOKEN }}
          for chart in .cr-release-packages/*.tgz; do
            helm push "$chart" oci://ghcr.io/subshell/helm
          done
