name: Release Charts

on:
  # TODO push will be removed before merge
  push:
    branches:
      - SUDO-610_oci_helmcharts
  workflow_run:
    workflows:
      - Test Charts
    branches:
      - main
    types:
      - completed

jobs:
  release:
    if: ${{ github.repository == 'subshell/helm-charts'}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      # TODO step will be uncommented before merge
      #- name: Run chart-releaser
      #  uses: helm/chart-releaser-action@v1.7.0
      #  env:
      #    CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      # TODO step will be removed before merge

      - name: Download previous chart releases
        run: |
          mkdir -p .cr-release-packages
          # list releases and download assets
          PER_PAGE=100
          PAGE=1
          RELEASES_URL="https://api.github.com/repos/subshell/helm-charts/releases?per_page=${PER_PAGE}"
          CUTOFF_DATE="2025-01-01"

          while true; do
            OUTPUT_FILE="releases_page_${PAGE}.json"
            HEADERS_FILE="headers_${PAGE}.txt"
            
            echo "getting page with relases ${RELEASES_URL}"
            curl --fail --no-progress-meter -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${MY_TOKEN}" -H "X-GitHub-Api-Version: 2026-03-10" "${RELEASES_URL}" -o "${OUTPUT_FILE}" --dump-header "${HEADERS_FILE}"
            
            COUNT=$(jq 'length' "$OUTPUT_FILE")
            echo "Page ${PAGE} has ${COUNT} releases"
            # note: 'grep -oP' uses Perl-compatible regex, '(?<=<)' Lookbehind '<', '[\S]*' Match zero or more non-whitespace characters, '(?=>; rel="next")' Lookahead: must be followed by '>; rel="next"'
            RELEASES_URL=$(grep 'link:' "${HEADERS_FILE}" | grep -oP '(?<=<)[\S]*(?=>; rel="next")' || true)

            if [ -z "$RELEASES_URL" ]; then
              echo "no next page, stopping"
              break
            fi
            
            PAGE=$((PAGE + 1))
          done
          # download release assets
          REMAINING=( "sophora-server-2.9.1.tgz sophora-server-3.0.0.tgz sophora-server-3.0.1.tgz sophora-server-3.1.0.tgz sophora-server-3.1.1.tgz sophora-server-3.1.2.tgz sophora-server-3.2.0.tgz sophora-server-3.3.0.tgz sophora-server-3.4.0.tgz sophora-tablestar-controller-1.0.0.tgz sophora-tablestar-controller-1.0.1.tgz sophora-tablestar-controller-1.0.2.tgz sophora-tablestar-controller-1.1.0.tgz sophora-ugc-1.0.0.tgz sophora-ugc-1.0.1.tgz sophora-ugc-1.0.2.tgz sophora-ugc-1.0.3.tgz sophora-ugc-2.0.0.tgz sophora-ugc-2.0.1.tgz sophora-ugc-2.0.10.tgz sophora-ugc-2.0.11.tgz sophora-ugc-2.0.12.tgz sophora-ugc-2.0.13.tgz sophora-ugc-2.0.14.tgz sophora-ugc-2.0.15.tgz sophora-ugc-2.0.2.tgz sophora-ugc-2.0.3.tgz sophora-ugc-2.0.4.tgz sophora-ugc-2.0.5.tgz sophora-ugc-2.0.6.tgz sophora-ugc-2.0.7.tgz sophora-ugc-2.0.8.tgz sophora-ugc-2.0.9.tgz sophora-ugc-2.1.0.tgz sophora-ugc-2.2.0.tgz sophora-ugc-2.2.1.tgz sophora-ugc-2.3.0.tgz sophora-ugc-2.4.0.tgz sophora-ugc-proxy-1.0.0.tgz sophora-ugc-proxy-1.0.1.tgz sophora-ugc-proxy-1.0.2.tgz sophora-ugc-proxy-1.1.0.tgz sophora-webclient-1.0.0.tgz sophora-webclient-1.0.1.tgz sophora-webclient-1.1.0.tgz sophora-webclient-1.2.0.tgz sophora-webclient-1.2.1.tgz sophora-webclient-1.2.2.tgz sophora-webclient-1.3.0.tgz sophora-webclient-1.4.0.tgz sophora-webclient-1.4.2.tgz sophora-webclient-1.4.3.tgz sophora-webclient-1.4.4.tgz sophora-webclient-1.4.5.tgz sophora-webclient-1.5.0.tgz sophora-webclient-1.5.1.tgz sophora-webclient-1.6.0.tgz sophora-youtube-connector-1.0.0.tgz sophora-youtube-connector-1.1.0.tgz sophora-youtube-connector-1.2.0.tgz sophora-youtube-connector-1.2.1.tgz sophora-youtube-connector-1.2.3.tgz sophora-youtube-connector-1.2.4.tgz sophora-youtube-connector-1.3.0.tgz sophora-youtube-connector-1.4.0.tgz sophora-youtube-connector-1.5.0.tgz youtube-connector-1.0.0.tgz" )
          for chartUrl in $(jq -r '.[].assets[].browser_download_url' releases_page_*.json); do
            FILENAME="${chartUrl##*/}"
            if [[ ! " ${REMAINING[*]} " =~ " ${FILENAME} " ]]; then
              echo "skipping $FILENAME (not in remaining list)"
              continue
            fi
            echo "downloading $chartUrl"
            curl --fail --no-progress-meter -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${MY_TOKEN}" -H "X-GitHub-Api-Version: 2026-03-10" "${chartUrl}" --output-dir .cr-release-packages --remote-header-name -O
          done
          RELEASE_PACKAGES=( $(ls .cr-release-packages/) )
          echo "found ${#RELEASE_PACKAGES[@]} files:"
          echo "${RELEASE_PACKAGES[*]}"
        env:
          MY_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Push charts to OCI registry
        if: ${{ hashFiles('.cr-release-packages/*.tgz') != '' }}
        run: |
          echo "${MY_TOKEN}" | helm registry login ghcr.io --username "${{ github.actor }}" --password-stdin
          for chart in .cr-release-packages/*.tgz; do
            echo "pushing ${chart} to OCI registry"
            helm push "$chart" oci://ghcr.io/subshell/helm-charts
          done
        env:
          MY_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
