image:
  repository: container.subshell.com/sophora/avtool/youtube-connector
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "3.0.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

javaOptions: "-Davtool.groovy.dir=/app/groovy -XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=80.0 -XX:+ExitOnOutOfMemoryError -XX:+PerfDisableSharedMem"

configGenerator:
  image:
    repository: "container.subshell.com/misc/alpine-toolkit"
    tag: "0.2.0"
    pullPolicy: IfNotPresent
  extraEnvVarsSecret:
  # Additional environment variables can be defined here
  env:

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  annotations: {}
  clusterIP: None
  httpPort: 8080

ingress:
  enabled: false
  # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
  # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
  # ingressClassName: nginx
  annotations: {}
  hosts:
  tls: []

# httpRoutes Map of HTTPRoute resources (Gateway API) to create.
# The map key is used as a suffix for the resource name, e.g. "web" -> "<fullname>-web".
httpRoutes: {}
  # web:
  #   # httpRoutes.web.parentRefs References to the Gateway resources that the HTTPRoute should attach to
  #   parentRefs:
  #     - name: my-gateway
  #       namespace: gateway-namespace
  #   # httpRoutes.web.hostnames Array with hostnames used for the HTTPRoute
  #   hostnames:
  #     - "my-service.example.com"
  #   # httpRoutes.web.matches Optional array of HTTPRouteMatch objects for matching HTTP requests
  #   matches:
  #     - path:
  #         type: PathPrefix
  #         value: /
  #   # httpRoutes.web.filters Optional array of HTTPRouteFilter objects for modifying requests/responses
  #   filters:
  #     - type: RequestHeaderModifier
  #       requestHeaderModifier:
  #         set:
  #           - name: X-Custom-Header
  #             value: custom-value
  #   # httpRoutes.web.annotations annotations for the HTTPRoute
  #   annotations: {}

serviceAccount:
  create:
  annotations:

resources:
  requests:
    cpu: 100m
    memory: 4Gi
  limits:
    memory: 4Gi

nodeSelector: {}

tolerations: []

affinity: {}

sophora:
  youtubeconnector:
    logback: |
      <?xml version="1.0" encoding="UTF-8"?>
      <configuration scan="true" scanPeriod="60 seconds">
      <jmxConfigurator/>

      <!-- Propagate level settings to java.util.logging. -->
      <contextListener class="ch.qos.logback.classic.jul.LevelChangePropagator"/>

      <appender class="ch.qos.logback.core.rolling.RollingFileAppender" name="logfile">
      <File>logs/youtube-connector.log</File>
      <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
      <fileNamePattern>logs/youtube-connector.%d{yyyy-MM-dd}.log</fileNamePattern>
      <maxHistory>14</maxHistory>
      </rollingPolicy>
      <encoder>
      <pattern>[%d{"yyyy-MM-dd HH:mm:ss.SSSX",UTC}, %-5p] [%t] [UUID: %X{uuid}] [SOPHORA_ID: %X{sophora_id}] [USER: %X{user}] %c:%L: %m%n</pattern>
      </encoder>
      </appender>

      <appender class="ch.qos.logback.core.rolling.RollingFileAppender" name="errorLog">
      <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
      <level>ERROR</level>
      </filter>
      <File>logs/youtube-connector_error.log</File>
      <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
      <fileNamePattern>logs/youtube-connector_error.%d{yyyy-MM-dd}.log</fileNamePattern>
      <maxHistory>14</maxHistory>
      </rollingPolicy>
      <encoder>
      <pattern>[%d{"yyyy-MM-dd HH:mm:ss.SSSX",UTC}, %-5p] [%t] [UUID: %X{uuid}] [SOPHORA_ID: %X{sophora_id}] [USER: %X{user}] %c:%L: %m%n</pattern>
      </encoder>
      </appender>

      <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
      <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
      <level>INFO</level>
      </filter>
      <filter class="ch.qos.logback.classic.filter.LevelFilter">
      <level>ERROR</level>
      <onMatch>DENY</onMatch>
      <onMismatch>ACCEPT</onMismatch>
      </filter>
      <encoder>
      <pattern>[%d{"yyyy-MM-dd HH:mm:ss.SSSX",UTC}, %-5p] [%t] [UUID: %X{uuid}] [SOPHORA_ID: %X{sophora_id}] [USER: %X{user}] %m%n</pattern>
      </encoder>
      </appender>

      <appender name="STDERR" class="ch.qos.logback.core.ConsoleAppender">
      <target>System.err</target>
      <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
      <level>ERROR</level>
      </filter>
      <encoder>
      <pattern>[%d{"yyyy-MM-dd HH:mm:ss.SSSX",UTC}, %-5p] [%t] [UUID: %X{uuid}] [SOPHORA_ID: %X{sophora_id}] [USER: %X{user}] %c:%L: %m%n</pattern>
      </encoder>
      </appender>

      <logger name="com.subshell.sophora" level="INFO" />
      <logger name="com.subshell.sophora.avtool" level="INFO" />
      <logger name="com.subshell.sophora.avtool.youtube" level="INFO" />
      <logger name="sun.rmi" level="WARN" />
      <logger name="com.google" level="INFO" />

      <root level="WARN">
      <appender-ref ref="STDOUT" />
      <appender-ref ref="STDERR" />
      <appender-ref ref="logfile"/>
      <appender-ref ref="errorLog"/>
      </root>
      </configuration>

    mediaconfig:

    preprocessor:
      enabled:
      content:
      filename:

    config:
    # can be either 'properties' or 'yml'
    configFormat:

    secret:
      name: youtube-connector-credentials
      server:
        usernameKey: sophora-username
        passwordKey: sophora-password

    jobstore:
      storage:
        storageClass:
        resources: {}
    oauth:
      storage:
        storageClass:
        resources: {}
    extraEnvVarsSecret:
    # Additional environment variables can be defined here
    env:

extraInitContainers: []
extraVolumes: []
extraVolumeMounts: []

## @section GCP
##
## Specific for the use with GCP Kubernetes Clusters

gcp:
  # gcp.enabled Whether GCP resources should be enabled or not
  enabled: true
  # gcp.healthCheck.enabled Whether the GCP Health Check resource should be deployed
  # gcp.healthCheck.port Number of the port used for the GCP Health Check
  # gcp.healthCheck.portName Name of the port used for the GCP Health Check
  # gcp.healthCheck.path HTTP path GCP should use to check the application's health
  # gcp.healthCheck.logging Whether to enable access logging for GCP Health Check requests
  healthCheck:
    enabled: false
    logging: false
    port: 8080
    # note: Cannot use named port when using network endpoint group as backend.
    # portName: http-service
    path: "/health"
  # gcp.backendPolicy.enabled Whether the GCP Backend Policy resource should be deployed
  # gcp.backendPolicy.logging.enabled Whether to enable access logging for GCP Backend Policy requests
  # gcp.backendPolicy.logging.sampleRate Sample rate for GCP Backend Policy logging (1-1000000)
  # gcp.backendPolicy.sessionAffinity Type of session affinity for GCP Backend Policy (NONE, GENERATED_COOKIE, HTTP_COOKIE)
  # gcp.backendPolicy.cookieTtlSec TTL for session affinity cookies in seconds (only applicable for GENERATED_COOKIE and HTTP_COOKIE)
  # gcp.backendPolicy.connectionDraining.drainingTimeoutSec Timeout for GCP Backend Policy connection draining in seconds
  # gcp.backendPolicy.timeoutSec Timeout for GCP Backend Policy requests in seconds
  # gcp.backendPolicy.securityPolicy Name of the GCP Cloud Armor Security Policy to apply to the Backend Policy
  # gcp.backendPolicy.iap.enabled Whether to enable Identity-Aware Proxy (IAP) for the GCP Backend Policy
  # gcp.backendPolicy.iap.oauth2ClientSecretName Name of the Kubernetes secret containing the OAuth2 client secret for IAP
  # gcp.backendPolicy.iap.clientID OAuth2 client ID for IAP
  backendPolicy:
    enabled: false
  #  logging:
  #    enabled: false
  #    sampleRate: 1000000
  #  sessionAffinity:
  #    type: NONE
  #    cookieTtlSec: 0
  #  connectionDraining:
  #    drainingTimeoutSec: 0
  #  timeoutSec: 30
  #  securityPolicy: ""
  #  iap:
  #    enabled: false
  #    oauth2ClientSecretName: ""
  #    clientID: ""

# extraDeploy is a list of full Kubernetes manifests that will be rendered additionally by this chart
extraDeploy: []
