{{- if and .Values.clusterServerLb.enabled .Values.gcp.grpcHealthCheck.enabled (or .Values.clusterServerLb.grpcIngress.enabled .Values.clusterServerLb.grpcRoute.enabled .Values.clusterServerLb.grpcHttproute.enabled) }}
---
{{- $fullName := include "sophora-cluster-common.fullname" . -}}
{{- $labels := include "sophora-cluster-common.labels" . -}}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ printf "%s-grpc" ($fullName | trunc 58 | trimSuffix "-") }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  default:
    config:
      type: GRPC
      grpcHealthCheck:
        port: {{ .Values.clusterServerLb.service.grpcPort }}
    logConfig:
      enabled: {{ .Values.gcp.grpcHealthCheck.logging }}
  targetRef:
    group: ""
    kind: Service
    name: {{ .Values.clusterServerLb.name }}
{{- end }}
