{{- if .Values.clusterServerLb.enabled -}}
{{- $fullName := include "sophora-cluster-common.fullname" . -}}
{{- $labels := include "sophora-cluster-common.labels" . -}}
{{- $svcPort := .Values.clusterServerLb.service.grpcPort -}}
{{- range $nameSuffix := (.Values.clusterServerLb.grpcHttproutes | keys | sortAlpha) }}
{{- $httpRoute := index $.Values.clusterServerLb.grpcHttproutes $nameSuffix }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-%s" $fullName $nameSuffix | trunc 63 | trimSuffix "-" }}
  labels:
    {{- $labels | nindent 4 }}
  {{- with $httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $httpRoute.parentRefs }}
  parentRefs:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $httpRoute.hostnames }}
  hostnames:
  {{- range $httpRoute.hostnames }}
    - {{ . | quote }}
  {{- end }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ $.Values.clusterServerLb.name }}
          port: {{ $svcPort }}
      {{- with $httpRoute.matches }}
      matches:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $httpRoute.filters }}
      filters:
      {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
{{- end }}
