apiVersion: v2
name: opentelemetry-instrumentation
description: Simple OpenTelemetry Auto Instrumentation
type: application
version: 0.1.0
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "This is the first release of this helm chart."
appVersion: "1.16.0"
